<?php

/**
 * Scaffold
 * Light Weight PHP API Framework.
 *
 * Do not edit this file, instead, create a custom
 * bootstrap.php file in the application folder.
 * Editing this file could lead to unexpected results.
 *
 * @author Nathaniel Higgins http://nath.is
 * @author Claudio Albertin http://twitter.com/ClaudioAlbertin
 * @license GPL http://www.gnu.org/copyleft/gpl.html
 */

/**
 * Determine how long a particular request takes to compute.
 */
define('START', microtime(true));

/**
 * Determine if a file in the framework is being requested directly or
 * via the framework.
 */
define('SCAFFOLD', true);

/**
 * Access to the root folder, independent of the
 * location of the file using it.
 */
define('ROOT', pathinfo(__FILE__, PATHINFO_DIRNAME) . '/');

/**
 * Access to the system folder, independent of the
 * location of the file using it.
 */
define('SYSTEM', ROOT . 'system/');

/**
 * Access to the application folder, independent
 * of the location of the file using it.
 */
define('APPLICATION', ROOT . 'application/');

/**
 * Boot Scaffold
 */
require(SYSTEM . 'bootstrap.php');

$router = new Router;
$router->run();
